name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          git remote add hf https://SaiPavan12:$HF_TOKEN@huggingface.co/spaces/SaiPavan12/AI-Paper-Analyzer
          git push hf main --force
